source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Rover_Example', :exclusive => true do
  pod "Rover", :path => "../"
end

target 'Rover_Tests', :exclusive => true do
  pod "Rover", :path => "../"

  
end
