disabled_rules:
   # This rule interacts badly with Xcode, which typically fills in whitespace on blank lines between indented lines.
   - trailing_whitespace
   # As a stylistic choice the Rover SDK frequently features deeply defined data types, particularly in DTOs for the API.  This rule isn't appropriate for us.
   - nesting
   # This rule bans the use of `id` as an identifier.  Which is not helpful.
   - identifier_name
   # Sadly this would be great as a warning, but Swiftlint implements it as an error, and it cannot be adjusted.
   - line_length
   # https://github.com/RoverPlatform/rover-ios/issues/405
   - force_cast
   # All of the public API should have docstrings, but that's a much bigger project to implement. (disabled by default)
   - missing_docs
   # Our pattern for naming Extensions files conflicts with this rule.
   - file_name
   # We sometimes bundle multiple extensions into a single file.  Thus this rule can sometimes be excessively restrictive:
   - file_length
enabled_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_count
  - empty_string
  - explicit_init
  - explicit_self
  - fatal_error_message
  - file_name
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - operator_usage_whitespace
  - override_in_extension
  - pattern_matching_keywords
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_focused_test
  - redundant_nil_coalescing
  - required_enum_case
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - toggle_bool
  - trailing_closure
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - untyped_error_in_catch
  - unused_import
  - unused_private_declaration
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
excluded:
  - Sources/Data/Vendor/Reachability.swift
  